--oms表
omsprd,oms_orderinfo,orderinfoid,cretime
omsprd,oms_orderinfoitem,orderitemid,cre_time
omsprd,oms_tio,orderinfoid,cretime
omsprd,oms_crossdo,orderinfoid,cretime
omsprd,oms_crossdoitem,orderitemid,cretime
omsprd,oms_boxorder,boxid,cretime
omsprd,oms_boxorderitems,boxitemid,cretime
omsprd,oms_orderexpressnum,id,cretime
omsprd,oms_orderweight,id,cretime
omsprd,oms_pickingorder,id,cretime
omsprd,oms_waybill_state,id,create_time
omsprd,oms_waybill_flow_info,id,create_time
omsprd,oms_po,id,create_time
omsprd,oms_poitem,id,create_time
omsprd,oms_storage,id,in_time
omsprd,oms_cust_complaints,id,create_time
omsprd,oms_cust_complaints_record,id,operate_time
omsprd,oms_customer_warehouse_region,id,create_time
omsprd,log_api_record,id,cre_time
--public表
omsprd,pub_project,projectid,cretime
omsprd,pub_project_rule,id,cretime
omsprd,pub_region,regionid,cretime
omsprd,pub_customer,customerid,cretime
omsprd,pub_customer_contract,id,create_time
omsprd,pub_customer_linkmaninfo,id,create_time
omsprd,pub_carrier,carrierid,cretime
omsprd,pub_deliver,deliverid,cretime
omsprd,pub_product,productid,cretime
omsprd,pub_productcategory,categoryid,cretime
omsprd,pub_warehouse,warehouseid,cretime
omsprd,pub_billtype,ordertypeid,cretime
omsprd,pub_cust_complaints_reason,id,create_time
omsprd,pub_package_description,id,create_time
omsprd,pub_carrier_servicetype,id,cretime
omsprd,pub_cuscarrier_monpayaccount,id,cretime
--system表
omsprd,system_code,id,create_dt
omsprd,system_code_type,id,create_dt
--wms库
wms,wms_do,id,cre_time
wms,wms_do_items,id,cre_time
wms,wms_task,id,cre_time
wms,wms_task_item,id,cre_time
wms,wms_do_expressnum,id,cre_time
wms,wms_do_allocation_items,ID,in_time
wms,wms_pick_assign,id,receive_time
wms,wms_pick_record,id,create_time
wms,wms_recheck_check,id,cre_time
wms,wms_recheck_item,id,operator_time
wms,wms_order_weight,id,cre_time
wms,wms_box_order,id,cre_time
wms,wms_box_items,id,cre_time
wms,wms_packmaterial,id,cre_time
wms,wms_scanrecord_expressnum,id,cre_time
wms,wms_location,id,cre_time
wms,wms_po,id,cre_time
wms,wms_po_items,id,cre_time
wms,wms_po_rec_order,id,cre_time
wms,wms_po_rec_order_items,id,rec_confirm_time
wms,wms_po_rec_putup_detail,id,putup_time
wms,wms_storage,id,in_time
wms,wms_to,id,cre_time
wms,wms_location_type,id,cre_time
wms,wms_location_fuctype,id,cre_time
wms,wms_storage_backup,id,cur_time
wms,wms_storage_update,id,cre_time
wms,wms_future_delivery,id,cre_time
wms,wms_task_list,id,cre_time
wms,wms_adjustment,id,cre_time
wms,wms_adjustment_items,id,cre_time
wms,wms_transform_items,id,cre_time
wms,wms_transform,id,cre_time
wms,system_code,id,create_dt
wms,pub_packmaterial,id,cre_time
wms,wms_area,id,cre_time
wms,wms_subhouse,id,cre_time
wms,wms_replenishment,id,cre_time
wms,wms_replenishment_task,id,cre_time
wms,wms_stocktake,id,cre_time
wms,wms_stocktake_items,id,cre_time
wms,wms_stocktake_task,id,cre_time
wms,wms_stocktake_task_item,id,cre_time
wms,wms_future_delivery_log,id,oper_time
wms,wms_storage_extension,id,modtime
--bms
bmssite_prd,biz_dispatch_bill,id,create_time
bmssite_prd,bill_check_info,id,create_time
bmssite_prd,fees_receive_storage,id,create_time
bmssite_prd,fees_receive_dispatch,id,create_time
bmssite_prd,fees_abnormal,id,create_time
bmssite_prd,biz_pallet_info,id,create_time
bmssite_prd,pub_customer,id,create_time
bmssite_prd,pub_customer_base,id,create_time
bmssite_prd,bms_group,id,create_time
bmssite_prd,bms_group_subject,id,create_time
bmssite_prd,biz_dispatch_package,id,cre_time
--contract
contract,contract_custom_base,id,create_time
contract,contract_custom_sub,id,create_time
--csp
csp,csp_category_relation,id,cre_time
csp,csp_category_group,id,cre_time
csp,csp_category,id,cre_time
csp,csp_form_info,id,cre_time
csp,csp_form_system,id,cre_time
csp,csp_form_deal_category,id,cre_time
--bak
omsprd_bak,extract_product_receive_bak,id,cretime
omsprd_bak,log_api_record_bak,id,cre_time
omsprd_bak,oms_message_bak,auto_id,opertime
omsprd_bak,oms_order_operation_log_bak,id,oper_time
omsprd_bak,oms_orderinfo_bak,orderinfoid,cretime
omsprd_bak,oms_orderinfoitem_bak,orderitemid,cre_time
omsprd_bak,oms_status_upload_do,id,op_time
omsprd_bak,oms_tio_bak,orderinfoid,cretime
omsprd_bak,oms_to_bak,id,cre_time
omsprd_bak,oms_waybill_flow_info_bak,id,create_time
