// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

package com.jiuye.mcp.protobuf;

public final class MessageType {
  private MessageType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MessageTypeBase}
   */
  public enum MessageTypeBase
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AUTH = 1;</code>
     *
     * <pre>
     **
     * 验证
     * </pre>
     */
    AUTH(0, 1),
    /**
     * <code>PING = 2;</code>
     *
     * <pre>
     **
     * 客户端到服务端ping
     * </pre>
     */
    PING(1, 2),
    /**
     * <code>PONG = 3;</code>
     *
     * <pre>
     **
     * 服务端到客户端pong
     * </pre>
     */
    PONG(2, 3),
    /**
     * <code>UPLOAD_DATA = 4;</code>
     *
     * <pre>
     **
     * 客户端上传数据到服务端
     * </pre>
     */
    UPLOAD_DATA(3, 4),
    /**
     * <code>PUSH_DATA = 5;</code>
     *
     * <pre>
     **
     * 服务端推送数据到客户端
     * </pre>
     */
    PUSH_DATA(4, 5),
    /**
     * <code>AUTH_BACK = 11;</code>
     *
     * <pre>
     **
     * 验证返回
     * </pre>
     */
    AUTH_BACK(5, 11),
    /**
     * <code>UPLOAD_DATA_BACK = 14;</code>
     */
    UPLOAD_DATA_BACK(6, 14),
    /**
     * <code>PUSH_DATA_BACK = 15;</code>
     */
    PUSH_DATA_BACK(7, 15),
    /**
     * <code>COLUMN_PK = 16;</code>
     *
     * <pre>
     **
     * 客户端将PK信息发送给服务端
     * </pre>
     */
    COLUMN_PK(8, 16),
    /**
     * <code>SERVER_REJECT_AGENT_CONNECTION = 17;</code>
     *
     * <pre>
     **
     *   服务端拒绝客户端连接
     * </pre>
     */
    SERVER_REJECT_AGENT_CONNECTION(9, 17),
    ;

    /**
     * <code>AUTH = 1;</code>
     *
     * <pre>
     **
     * 验证
     * </pre>
     */
    public static final int AUTH_VALUE = 1;
    /**
     * <code>PING = 2;</code>
     *
     * <pre>
     **
     * 客户端到服务端ping
     * </pre>
     */
    public static final int PING_VALUE = 2;
    /**
     * <code>PONG = 3;</code>
     *
     * <pre>
     **
     * 服务端到客户端pong
     * </pre>
     */
    public static final int PONG_VALUE = 3;
    /**
     * <code>UPLOAD_DATA = 4;</code>
     *
     * <pre>
     **
     * 客户端上传数据到服务端
     * </pre>
     */
    public static final int UPLOAD_DATA_VALUE = 4;
    /**
     * <code>PUSH_DATA = 5;</code>
     *
     * <pre>
     **
     * 服务端推送数据到客户端
     * </pre>
     */
    public static final int PUSH_DATA_VALUE = 5;
    /**
     * <code>AUTH_BACK = 11;</code>
     *
     * <pre>
     **
     * 验证返回
     * </pre>
     */
    public static final int AUTH_BACK_VALUE = 11;
    /**
     * <code>UPLOAD_DATA_BACK = 14;</code>
     */
    public static final int UPLOAD_DATA_BACK_VALUE = 14;
    /**
     * <code>PUSH_DATA_BACK = 15;</code>
     */
    public static final int PUSH_DATA_BACK_VALUE = 15;
    /**
     * <code>COLUMN_PK = 16;</code>
     *
     * <pre>
     **
     * 客户端将PK信息发送给服务端
     * </pre>
     */
    public static final int COLUMN_PK_VALUE = 16;
    /**
     * <code>SERVER_REJECT_AGENT_CONNECTION = 17;</code>
     *
     * <pre>
     **
     *   服务端拒绝客户端连接
     * </pre>
     */
    public static final int SERVER_REJECT_AGENT_CONNECTION_VALUE = 17;


    public final int getNumber() { return value; }

    public static MessageTypeBase valueOf(int value) {
      switch (value) {
        case 1: return AUTH;
        case 2: return PING;
        case 3: return PONG;
        case 4: return UPLOAD_DATA;
        case 5: return PUSH_DATA;
        case 11: return AUTH_BACK;
        case 14: return UPLOAD_DATA_BACK;
        case 15: return PUSH_DATA_BACK;
        case 16: return COLUMN_PK;
        case 17: return SERVER_REJECT_AGENT_CONNECTION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageTypeBase>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageTypeBase>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageTypeBase>() {
            public MessageTypeBase findValueByNumber(int number) {
              return MessageTypeBase.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jiuye.mcp.protobuf.MessageType.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageTypeBase[] VALUES = values();

    public static MessageTypeBase valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageTypeBase(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageTypeBase)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageType.proto*\273\001\n\017MessageTypeBase\022" +
      "\010\n\004AUTH\020\001\022\010\n\004PING\020\002\022\010\n\004PONG\020\003\022\017\n\013UPLOAD_" +
      "DATA\020\004\022\r\n\tPUSH_DATA\020\005\022\r\n\tAUTH_BACK\020\013\022\024\n\020" +
      "UPLOAD_DATA_BACK\020\016\022\022\n\016PUSH_DATA_BACK\020\017\022\r" +
      "\n\tCOLUMN_PK\020\020\022\"\n\036SERVER_REJECT_AGENT_CON" +
      "NECTION\020\021B%\n\026com.jiuye.mcp.protobufB\013Mes" +
      "sageType"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
