// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.jiuye.mcp.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageBaseOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

    // required string agentId = 1;
    /**
     * <code>required string agentId = 1;</code>
     */
    boolean hasAgentId();
    /**
     * <code>required string agentId = 1;</code>
     */
    java.lang.String getAgentId();
    /**
     * <code>required string agentId = 1;</code>
     */
    com.google.protobuf.ByteString
    getAgentIdBytes();

    // required .MessageTypeBase type = 2;
    /**
     * <code>required .MessageTypeBase type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .MessageTypeBase type = 2;</code>
     */
    com.jiuye.mcp.protobuf.MessageType.MessageTypeBase getType();

    // optional string data = 3;
    /**
     * <code>optional string data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 3;</code>
     */
    com.google.protobuf.ByteString
    getDataBytes();
  }
  /**
   * Protobuf type {@code MessageBase}
   */
  public static final class MessageBase extends
          com.google.protobuf.GeneratedMessage
          implements MessageBaseOrBuilder {
    // Use MessageBase.newBuilder() to construct.
    private MessageBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageBase defaultInstance;
    public static MessageBase getDefaultInstance() {
      return defaultInstance;
    }

    public MessageBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageBase(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              agentId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.jiuye.mcp.protobuf.MessageType.MessageTypeBase value = com.jiuye.mcp.protobuf.MessageType.MessageTypeBase.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.jiuye.mcp.protobuf.Message.internal_static_MessageBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.jiuye.mcp.protobuf.Message.internal_static_MessageBase_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.jiuye.mcp.protobuf.Message.MessageBase.class, com.jiuye.mcp.protobuf.Message.MessageBase.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageBase> PARSER =
            new com.google.protobuf.AbstractParser<MessageBase>() {
              public MessageBase parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new MessageBase(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string agentId = 1;
    public static final int AGENTID_FIELD_NUMBER = 1;
    private java.lang.Object agentId_;
    /**
     * <code>required string agentId = 1;</code>
     */
    public boolean hasAgentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string agentId = 1;</code>
     */
    public java.lang.String getAgentId() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          agentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string agentId = 1;</code>
     */
    public com.google.protobuf.ByteString
    getAgentIdBytes() {
      java.lang.Object ref = agentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        agentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .MessageTypeBase type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.jiuye.mcp.protobuf.MessageType.MessageTypeBase type_;
    /**
     * <code>required .MessageTypeBase type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MessageTypeBase type = 2;</code>
     */
    public com.jiuye.mcp.protobuf.MessageType.MessageTypeBase getType() {
      return type_;
    }

    // optional string data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public com.google.protobuf.ByteString
    getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      agentId_ = "";
      type_ = com.jiuye.mcp.protobuf.MessageType.MessageTypeBase.AUTH;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAgentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAgentIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, getAgentIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jiuye.mcp.protobuf.Message.MessageBase parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jiuye.mcp.protobuf.Message.MessageBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageBase}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements com.jiuye.mcp.protobuf.Message.MessageBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.jiuye.mcp.protobuf.Message.internal_static_MessageBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.jiuye.mcp.protobuf.Message.internal_static_MessageBase_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.jiuye.mcp.protobuf.Message.MessageBase.class, com.jiuye.mcp.protobuf.Message.MessageBase.Builder.class);
      }

      // Construct using com.jiuye.mcp.protobuf.Message.MessageBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        agentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.jiuye.mcp.protobuf.MessageType.MessageTypeBase.AUTH;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.jiuye.mcp.protobuf.Message.internal_static_MessageBase_descriptor;
      }

      public com.jiuye.mcp.protobuf.Message.MessageBase getDefaultInstanceForType() {
        return com.jiuye.mcp.protobuf.Message.MessageBase.getDefaultInstance();
      }

      public com.jiuye.mcp.protobuf.Message.MessageBase build() {
        com.jiuye.mcp.protobuf.Message.MessageBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jiuye.mcp.protobuf.Message.MessageBase buildPartial() {
        com.jiuye.mcp.protobuf.Message.MessageBase result = new com.jiuye.mcp.protobuf.Message.MessageBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.agentId_ = agentId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jiuye.mcp.protobuf.Message.MessageBase) {
          return mergeFrom((com.jiuye.mcp.protobuf.Message.MessageBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jiuye.mcp.protobuf.Message.MessageBase other) {
        if (other == com.jiuye.mcp.protobuf.Message.MessageBase.getDefaultInstance()) return this;
        if (other.hasAgentId()) {
          bitField0_ |= 0x00000001;
          agentId_ = other.agentId_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000004;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAgentId()) {

          return false;
        }
        if (!hasType()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.jiuye.mcp.protobuf.Message.MessageBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jiuye.mcp.protobuf.Message.MessageBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string agentId = 1;
      private java.lang.Object agentId_ = "";
      /**
       * <code>required string agentId = 1;</code>
       */
      public boolean hasAgentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string agentId = 1;</code>
       */
      public java.lang.String getAgentId() {
        java.lang.Object ref = agentId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
          agentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string agentId = 1;</code>
       */
      public com.google.protobuf.ByteString
      getAgentIdBytes() {
        java.lang.Object ref = agentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          agentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string agentId = 1;</code>
       */
      public Builder setAgentId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string agentId = 1;</code>
       */
      public Builder clearAgentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        agentId_ = getDefaultInstance().getAgentId();
        onChanged();
        return this;
      }
      /**
       * <code>required string agentId = 1;</code>
       */
      public Builder setAgentIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        agentId_ = value;
        onChanged();
        return this;
      }

      // required .MessageTypeBase type = 2;
      private com.jiuye.mcp.protobuf.MessageType.MessageTypeBase type_ = com.jiuye.mcp.protobuf.MessageType.MessageTypeBase.AUTH;
      /**
       * <code>required .MessageTypeBase type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MessageTypeBase type = 2;</code>
       */
      public com.jiuye.mcp.protobuf.MessageType.MessageTypeBase getType() {
        return type_;
      }
      /**
       * <code>required .MessageTypeBase type = 2;</code>
       */
      public Builder setType(com.jiuye.mcp.protobuf.MessageType.MessageTypeBase value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .MessageTypeBase type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.jiuye.mcp.protobuf.MessageType.MessageTypeBase.AUTH;
        onChanged();
        return this;
      }

      // optional string data = 3;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public com.google.protobuf.ByteString
      getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setData(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setDataBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageBase)
    }

    static {
      defaultInstance = new MessageBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageBase)
  }

  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_MessageBase_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_MessageBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rMessage.proto\032\021MessageType.proto\"L\n\013Me" +
                    "ssageBase\022\017\n\007agentId\030\001 \002(\t\022\036\n\004type\030\002 \002(\016" +
                    "2\020.MessageTypeBase\022\014\n\004data\030\003 \001(\tB!\n\026com." +
                    "jiuye.mcp.protobufB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_MessageBase_descriptor =
                        getDescriptor().getMessageTypes().get(0);
                internal_static_MessageBase_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_MessageBase_descriptor,
                        new java.lang.String[] { "AgentId", "Type", "Data", });
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                            com.jiuye.mcp.protobuf.MessageType.getDescriptor(),
                    }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
